language: swift
osx_image: xcode10.1
xcode_workspace: waosSwift.xcworkspace
xcode_scheme: waosSwift
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
cache:
  - bundler
before_install:
  - bundle install
  - bundle update
script:
  - swiftlint --reporter junit
  - bundle exec fastlane ios unit_test