language: swift
osx_image: xcode10.2
xcode_workspace: waosSwift.xcworkspace
xcode_scheme: waosSwift
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
cache:
  directories:
  - Carthage
before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - rvm use $RVM_RUBY_VERSION #slather
before_script:
  - carthage update --no-build
  - (cd Carthage/Checkouts/ReactorKit && swift package generate-xcodeproj)
  - carthage build --platform iOS --no-use-binaries --cache-builds
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success:
  - fastlane lint
  - fastlane test