language: swift
osx_image: xcode10.1
xcode_workspace: waosSwift.xcworkspace
xcode_scheme: waosSwift
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
cache:
  - bundler
before_install:
  - rvm use $RVM_RUBY_VERSION #slather
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success:
  - fastlane lint
  - fastlane test