language: swift
osx_image: xcode12
xcode_workspace: waosSwift.xcworkspace
xcode_scheme: waosSwift
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11
cache:
  bundler: true
  directories:
    - Carthage
before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - rvm use $RVM_RUBY_VERSION #slather
install: bundle install --without=documentation
before_script:
  - carthage bootstrap --no-build --new-resolver
  - (cd Carthage/Checkouts/ReactorKit && swift package generate-xcodeproj)
  - timeout 30m ./carthage-build.sh --platform iOS --no-use-binaries --cache-builds || true
after_success:
  - fastlane lint
  - fastlane test