language: swift
osx_image: xcode11.2
xcode_workspace: waosSwift.xcworkspace
xcode_scheme: waosSwift
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
cache:
  bundler: true
  directories:
  - Carthage
before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - rvm use $RVM_RUBY_VERSION #slather
install: bundle install --without=documentation
before_script:
  - carthage bootstrap --no-build --new-resolver
  - (cd Carthage/Checkouts/ReactorKit && swift package generate-xcodeproj)
  - carthage build --platform iOS --no-use-binaries --cache-builds
after_success:
  - fastlane lint
  - fastlane test